# Generated by Django 5.0.6 on 2024-11-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('Designer', 'Designer'), ('Other', 'Other')], max_length=50)),
                ('company_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_work_no', models.CharField(max_length=15)),
                ('registration_no', models.CharField(max_length=20)),
                ('vat_no', models.CharField(max_length=20)),
                ('physical_address', models.TextField()),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('PayPal', 'PayPal'), ('Bank Transfer', 'Bank Transfer')], max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('field1', models.CharField(blank=True, max_length=100, null=True)),
                ('field2', models.CharField(blank=True, max_length=100, null=True)),
                ('field3', models.CharField(blank=True, max_length=100, null=True)),
                ('field4', models.CharField(blank=True, max_length=100, null=True)),
                ('field5', models.CharField(blank=True, max_length=100, null=True)),
                ('field6', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
