# Generated by Django 5.0.6 on 2024-12-05 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiglo_dev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetail',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('telephone_number', models.BigIntegerField()),
                ('whatsapp_number', models.BigIntegerField()),
                ('password', models.CharField(max_length=30)),
                ('attribute1', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute2', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute3', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute4', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute5', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute6', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('created_by_user_id', models.IntegerField()),
                ('updated_on', models.DateField(auto_now=True)),
                ('updated_by_user_id', models.IntegerField(blank=True, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('salutation_code', models.ForeignKey(db_column='Salution_code', on_delete=django.db.models.deletion.CASCADE, to='opiglo_dev.salutationcode')),
            ],
            options={
                'db_table': 'opiglo_admin_detail',
            },
        ),
    ]
