# Generated by Django 5.0.6 on 2024-12-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiglo_dev', '0002_admindetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetail',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customerdetail',
            name='telephone_number',
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='attribute1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='contact_work_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='password',
            field=models.CharField(default='password@1234', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('PayPal', 'PayPal'), ('Bank Transfer', 'Bank Transfer')], default='Credit Card', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='physical_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='position',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Director', 'Director')], default='Owner', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='registration_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='vat_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
