# Generated by Django 5.0.6 on 2024-12-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiglo_dev', '0004_alter_customerdetail_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
    ]
