# Generated by Django 5.0.6 on 2024-12-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiglo_dev', '0006_alter_customerdetail_selected_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='selected_payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
