# Generated by Django 5.0.6 on 2024-12-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiglo_dev', '0007_alter_customerdetail_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
